export const lessons = [
  {
    id: 1,
    slug: "big-o-notation",
    title: "Big-O Notation & Complexity Analysis",
    phase: 1,
    phaseTitle: "Foundations",
    description:
      "Learn how to measure algorithm efficiency using time and space complexity. The foundation of everything.",
    xpReward: 100,
    icon: "Timer",
  },
  {
    id: 2,
    slug: "arrays-and-strings",
    title: "Arrays & Strings",
    phase: 1,
    phaseTitle: "Foundations",
    description:
      "Static & dynamic arrays, std::string, memory layout, and common patterns.",
    xpReward: 120,
    icon: "LayoutList",
  },
  {
    id: 3,
    slug: "recursion-and-backtracking",
    title: "Recursion & Backtracking",
    phase: 1,
    phaseTitle: "Foundations",
    description:
      "Recursive thinking, call stacks, base cases, and backtracking patterns.",
    xpReward: 130,
    icon: "Repeat",
  },
  {
    id: 4,
    slug: "linked-lists",
    title: "Linked Lists",
    phase: 2,
    phaseTitle: "Linear Structures",
    description: "Singly, doubly, circular linked lists and pointer mechanics.",
    xpReward: 130,
    icon: "Link",
  },
  {
    id: 5,
    slug: "stacks",
    title: "Stacks & Applications",
    phase: 2,
    phaseTitle: "Linear Structures",
    description: "LIFO principle, implementations, and real-world applications.",
    xpReward: 120,
    icon: "Layers",
  },
  {
    id: 6,
    slug: "queues",
    title: "Queues, Deques & Priority Queues",
    phase: 2,
    phaseTitle: "Linear Structures",
    description: "FIFO, circular queues, deques, and priority queue intro.",
    xpReward: 130,
    icon: "ListOrdered",
  },
  {
    id: 7,
    slug: "hash-tables",
    title: "Hash Tables & Hash Maps",
    phase: 3,
    phaseTitle: "Hashing",
    description:
      "Hash functions, collision handling, and unordered_map in C++.",
    xpReward: 140,
    icon: "Hash",
  },
  {
    id: 8,
    slug: "hash-sets",
    title: "Hash Sets & Real-World Patterns",
    phase: 3,
    phaseTitle: "Hashing",
    description: "Deduplication, unordered_set, and practical use cases.",
    xpReward: 120,
    icon: "CircleDot",
  },
  {
    id: 9,
    slug: "binary-trees",
    title: "Binary Trees & Traversals",
    phase: 4,
    phaseTitle: "Trees",
    description: "Tree terminology, BFS/DFS traversals, recursive thinking.",
    xpReward: 150,
    icon: "GitBranch",
  },
  {
    id: 10,
    slug: "binary-search-trees",
    title: "Binary Search Trees",
    phase: 4,
    phaseTitle: "Trees",
    description: "Insert, delete, search operations and balancing issues.",
    xpReward: 150,
    icon: "Search",
  },
  {
    id: 11,
    slug: "balanced-bsts",
    title: "Balanced BSTs (AVL / Red-Black)",
    phase: 4,
    phaseTitle: "Trees",
    description: "Self-balancing trees, rotations, and when to use them.",
    xpReward: 170,
    icon: "Scale",
  },
  {
    id: 12,
    slug: "heaps",
    title: "Heaps & Priority Queues",
    phase: 4,
    phaseTitle: "Trees",
    description: "Min/max heaps, heapify, and priority_queue in C++.",
    xpReward: 150,
    icon: "Triangle",
  },
  {
    id: 13,
    slug: "tries",
    title: "Tries (Prefix Trees)",
    phase: 4,
    phaseTitle: "Trees",
    description: "Autocomplete, word search, and trie implementation.",
    xpReward: 160,
    icon: "FileText",
  },
  {
    id: 14,
    slug: "graph-fundamentals",
    title: "Graph Fundamentals & Representations",
    phase: 5,
    phaseTitle: "Graphs",
    description:
      "Adjacency list/matrix, terminology, directed vs undirected graphs.",
    xpReward: 140,
    icon: "Share2",
  },
  {
    id: 15,
    slug: "graph-traversals",
    title: "BFS & DFS",
    phase: 5,
    phaseTitle: "Graphs",
    description: "Breadth-first and depth-first search, connected components.",
    xpReward: 150,
    icon: "Compass",
  },
  {
    id: 16,
    slug: "shortest-path",
    title: "Shortest Path Algorithms",
    phase: 5,
    phaseTitle: "Graphs",
    description: "Dijkstra and Bellman-Ford algorithms.",
    xpReward: 170,
    icon: "Route",
  },
  {
    id: 17,
    slug: "topological-sort",
    title: "Topological Sort & DAGs",
    phase: 5,
    phaseTitle: "Graphs",
    description: "Scheduling problems and Kahn's algorithm.",
    xpReward: 160,
    icon: "ArrowDownUp",
  },
  {
    id: 18,
    slug: "minimum-spanning-trees",
    title: "Minimum Spanning Trees",
    phase: 5,
    phaseTitle: "Graphs",
    description: "Kruskal's and Prim's algorithms.",
    xpReward: 160,
    icon: "Network",
  },
  {
    id: 19,
    slug: "union-find",
    title: "Union-Find (Disjoint Set Union)",
    phase: 5,
    phaseTitle: "Graphs",
    description: "Path compression, union by rank, applications.",
    xpReward: 160,
    icon: "Merge",
  },
  {
    id: 20,
    slug: "sorting-algorithms",
    title: "Sorting Algorithms",
    phase: 6,
    phaseTitle: "Sorting & Searching",
    description:
      "Merge sort, quick sort, counting sort, radix sort — theory, implementation, and trade-offs.",
    xpReward: 170,
    icon: "ArrowUpDown",
  },
  {
    id: 21,
    slug: "binary-search",
    title: "Binary Search & Searching Patterns",
    phase: 6,
    phaseTitle: "Sorting & Searching",
    description:
      "Binary search templates, search space reduction, and classic interview patterns.",
    xpReward: 170,
    icon: "Search",
  },
  {
    id: 22,
    slug: "dp-fundamentals",
    title: "DP Fundamentals",
    phase: 7,
    phaseTitle: "Dynamic Programming",
    description:
      "Memoization vs tabulation, optimal substructure, overlapping subproblems.",
    xpReward: 170,
    icon: "Brain",
  },
  {
    id: 23,
    slug: "dp-1d",
    title: "1D Dynamic Programming",
    phase: 7,
    phaseTitle: "Dynamic Programming",
    description: "Fibonacci, climbing stairs, house robber patterns.",
    xpReward: 160,
    icon: "TrendingUp",
  },
  {
    id: 24,
    slug: "dp-2d",
    title: "2D Dynamic Programming",
    phase: 7,
    phaseTitle: "Dynamic Programming",
    description: "Grid problems, LCS, edit distance.",
    xpReward: 180,
    icon: "Grid3x3",
  },
  {
    id: 25,
    slug: "dp-strings",
    title: "DP on Strings",
    phase: 7,
    phaseTitle: "Dynamic Programming",
    description: "Palindromes, subsequences, pattern matching.",
    xpReward: 180,
    icon: "Type",
  },
  {
    id: 26,
    slug: "dp-trees-graphs",
    title: "DP on Trees & Graphs",
    phase: 7,
    phaseTitle: "Dynamic Programming",
    description: "Tree DP, shortest paths revisited.",
    xpReward: 190,
    icon: "GitFork",
  },
  {
    id: 27,
    slug: "dp-knapsack",
    title: "Knapsack Family",
    phase: 7,
    phaseTitle: "Dynamic Programming",
    description: "0/1 knapsack, unbounded, partition problems.",
    xpReward: 180,
    icon: "Package",
  },
  {
    id: 28,
    slug: "dp-interval-state",
    title: "Interval & State DP",
    phase: 7,
    phaseTitle: "Dynamic Programming",
    description: "Matrix chain multiplication, bitmask DP.",
    xpReward: 200,
    icon: "Puzzle",
  },
  {
    id: 29,
    slug: "segment-fenwick-trees",
    title: "Segment Trees & Fenwick Trees",
    phase: 8,
    phaseTitle: "Advanced Structures",
    description: "Range queries, lazy propagation, prefix sums.",
    xpReward: 200,
    icon: "BarChart3",
  },
  {
    id: 30,
    slug: "advanced-structures",
    title: "B-Trees, Skip Lists, Bloom Filters",
    phase: 8,
    phaseTitle: "Advanced Structures",
    description: "Database indexing and probabilistic data structures.",
    xpReward: 190,
    icon: "Database",
  },
  {
    id: 31,
    slug: "choosing-data-structures",
    title: "Choosing the Right Data Structure",
    phase: 9,
    phaseTitle: "Mastery",
    description: "Decision framework and trade-off analysis.",
    xpReward: 150,
    icon: "CheckCircle",
  },
  {
    id: 32,
    slug: "google-interview-patterns",
    title: "Google-Style Interview Patterns",
    phase: 9,
    phaseTitle: "Mastery",
    description: "Common DS+DP combinations and system design implications.",
    xpReward: 200,
    icon: "Trophy",
  },
];

export const phases = [
  { id: 1, title: "Foundations", color: "#6366f1" },
  { id: 2, title: "Linear Structures", color: "#8b5cf6" },
  { id: 3, title: "Hashing", color: "#a855f7" },
  { id: 4, title: "Trees", color: "#22c55e" },
  { id: 5, title: "Graphs", color: "#3b82f6" },
  { id: 6, title: "Sorting & Searching", color: "#06b6d4" },
  { id: 7, title: "Dynamic Programming", color: "#f59e0b" },
  { id: 8, title: "Advanced Structures", color: "#ef4444" },
  { id: 9, title: "Mastery", color: "#f97316" },
];
